from sys import argv
# This file looks at a map file generated by the linker and compares it with 
# object files and the archive files to find out what third-party functions
# are used.

# gcc -c <source-file.c>
# ld -Map output.map -N -o <name of executable> <object_file> -lssl -lcrypto
def main():
    prev_line = ""
    archive_files = []
    functions = []
    for i in range(len(argv)):
        if i == 1:
            map_file = argv[i]
        if i == 2:
            object_file = argv[i]
        elif i > 2:
            archive_files.append(argv[i])
    f1 = open(map_file, "r")
    lines = f1.readlines()
    max = 5
    count = 1
    for line in lines:
        if count <= max:
            #print(line)
            count += 1
        for a in archive_files:
            if a in prev_line and " " + object_file + " " in line:
                functions.append(line)
        prev_line = line
    f1.close()
    f2 = open("object_file_functions.txt", "w")
    for f in functions:
        f = f.replace(' ','')
        f = f.replace(object_file, '')
        f = f.replace('(', '')
        f = f.replace(')', '')
        print(f)
        f2.write(f)
    f2.close()
    return 0

if __name__ == '__main__':
    main()
